"""add_ai_audit_fields

Revision ID: 01c8b8690a57
Revises: a67f9b490b81
Create Date: 2025-11-04 11:17:25.074569

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01c8b8690a57"
down_revision: Union[str, Sequence[str], None] = "a67f9b490b81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_locked", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("locked_until", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locked_until")
    op.drop_column("users", "is_locked")
    # ### end Alembic commands ###
