"""phase1_model_refinements

Revision ID: 11bf165b1dde
Revises: ea34083b61dd
Create Date: 2025-09-26 22:52:27.452953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11bf165b1dde'
down_revision: Union[str, Sequence[str], None] = 'ea34083b61dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing status values to title case for casting
    op.execute("UPDATE leaves SET status = 'Pending' WHERE status = 'PENDING'")
    op.execute("UPDATE leaves SET status = 'Approved' WHERE status = 'APPROVED'")
    op.execute("UPDATE leaves SET status = 'Rejected' WHERE status = 'REJECTED'")
    op.execute("UPDATE leaves SET status = 'Cancelled' WHERE status = 'CANCELLED'")
    op.execute("UPDATE shifts SET status = 'Pending' WHERE status = 'PENDING'")
    op.execute("UPDATE shifts SET status = 'Assigned' WHERE status = 'ASSIGNED'")
    op.execute("UPDATE shifts SET status = 'Completed' WHERE status = 'COMPLETED'")
    op.execute("UPDATE shifts SET status = 'Cancelled' WHERE status = 'CANCELLED'")

    # Create enums first
    leavestatus = sa.Enum('Pending', 'Approved', 'Rejected', 'Cancelled', name='leavestatus')
    leavestatus.create(op.get_bind())
    shiftstatus = sa.Enum('Pending', 'Assigned', 'Completed', 'Cancelled', name='shiftstatus')
    shiftstatus.create(op.get_bind())

    op.add_column('leaves', sa.Column('type', sa.String(), nullable=False))
    op.add_column('leaves', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('leaves', sa.Column('end_at', sa.DateTime(), nullable=False))
    op.alter_column('leaves', 'status',
               existing_type=sa.VARCHAR(),
               type_=leavestatus,
               existing_nullable=True,
               postgresql_using='status::leavestatus')
    op.drop_index(op.f('ix_leaves_company_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_employee_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_constraint(op.f('leaves_approved_by_fkey'), 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'start_date')
    op.drop_column('leaves', 'reason')
    op.drop_column('leaves', 'approved_by')
    op.drop_column('leaves', 'leave_type')
    op.drop_column('leaves', 'end_date')
    op.add_column('shifts', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('shifts', sa.Column('end_at', sa.DateTime(), nullable=False))
    op.alter_column('shifts', 'status',
               existing_type=sa.VARCHAR(),
               type_=shiftstatus,
               existing_nullable=True,
               postgresql_using='status::shiftstatus')
    op.drop_index(op.f('ix_shifts_company_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_employee_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_constraint(op.f('shifts_assigned_by_fkey'), 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'end_time')
    op.drop_column('shifts', 'shift_type')
    op.drop_column('shifts', 'notes')
    op.drop_column('shifts', 'start_time')
    op.drop_column('shifts', 'assigned_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('shifts', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('shift_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('shifts_assigned_by_fkey'), 'shifts', 'users', ['assigned_by'], ['id'])
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_employee_id'), 'shifts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shifts_company_id'), 'shifts', ['company_id'], unique=False)
    op.alter_column('shifts', 'status',
               existing_type_=sa.Enum('Pending', 'Assigned', 'Completed', 'Cancelled', name='shiftstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('shifts', 'end_at')
    op.drop_column('shifts', 'start_at')
    op.add_column('leaves', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('leaves', sa.Column('leave_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('leaves', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('leaves_approved_by_fkey'), 'leaves', 'users', ['approved_by'], ['id'])
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.create_index(op.f('ix_leaves_employee_id'), 'leaves', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leaves_company_id'), 'leaves', ['company_id'], unique=False)
    op.alter_column('leaves', 'status',
               existing_type_=sa.Enum('Pending', 'Approved', 'Rejected', 'Cancelled', name='leavestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('leaves', 'end_at')
    op.drop_column('leaves', 'start_at')
    op.drop_column('leaves', 'type')
    # Drop enums
    sa.Enum('Pending', 'Approved', 'Rejected', 'Cancelled', name='leavestatus').drop(op.get_bind())
    sa.Enum('Pending', 'Assigned', 'Completed', 'Cancelled', name='shiftstatus').drop(op.get_bind())
    # ### end Alembic commands ###
