"""add_audit_chain_table

Revision ID: 3a3da1f4f764
Revises: a24444214bd9
Create Date: 2025-11-04 21:15:07.351014

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a3da1f4f764"
down_revision: Union[str, Sequence[str], None] = "a24444214bd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_chains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.String(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("current_hash", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("is_tampered", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.Index("ix_audit_chains_chain_id", "chain_id"),
        sa.Index("ix_audit_chains_company_id", "company_id"),
        sa.Index("ix_audit_chains_current_hash", "current_hash"),
        sa.Index("ix_audit_chains_event_type", "event_type"),
        sa.Index("ix_audit_chains_id", "id"),
        sa.Index("ix_audit_chains_is_tampered", "is_tampered"),
        sa.Index("ix_audit_chains_sequence_number", "sequence_number"),
        sa.Index("ix_audit_chains_user_id", "user_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("current_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_chains")
    # ### end Alembic commands ###
