"""phase2_add_approver_id_to_leave_and_shift

Revision ID: 3f1a5795ea16
Revises: 11bf165b1dde
Create Date: 2025-09-27 13:06:11.251370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1a5795ea16'
down_revision: Union[str, Sequence[str], None] = '11bf165b1dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('approver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leaves', 'users', ['approver_id'], ['id'])
    op.add_column('shifts', sa.Column('approver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shifts', 'users', ['approver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'approver_id')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'approver_id')
    # ### end Alembic commands ###
