"""Phase 2 model refinements: enums, FKs, relationships

Revision ID: 45e1c8c538b3
Revises: 3f1a5795ea16
Create Date: 2025-09-27 19:49:56.701488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45e1c8c538b3'
down_revision: Union[str, Sequence[str], None] = '3f1a5795ea16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enums first
    leavetype = sa.Enum('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'PERSONAL', name='leavetype')
    leavetype.create(op.get_bind())
    taskstatus = sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='taskstatus')
    taskstatus.create(op.get_bind())
    taskpriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority')
    taskpriority.create(op.get_bind())

    # Update existing data to match enum values
    op.execute("UPDATE tasks SET status = 'PENDING' WHERE status = 'Pending'")
    op.execute("UPDATE tasks SET status = 'IN_PROGRESS' WHERE status = 'In Progress'")
    op.execute("UPDATE tasks SET status = 'COMPLETED' WHERE status = 'Completed'")
    op.execute("UPDATE tasks SET status = 'OVERDUE' WHERE status = 'Overdue'")
    op.execute("UPDATE tasks SET priority = 'LOW' WHERE priority = 'Low'")
    op.execute("UPDATE tasks SET priority = 'MEDIUM' WHERE priority = 'Medium'")
    op.execute("UPDATE tasks SET priority = 'HIGH' WHERE priority = 'High'")

    op.add_column('leaves', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('leaves', sa.Column('approved_by', sa.Integer(), nullable=True))
    # Handle leave type conversion - convert varchar to enum
    op.execute("ALTER TABLE leaves ALTER COLUMN type DROP DEFAULT")
    op.execute("ALTER TABLE leaves ALTER COLUMN type TYPE VARCHAR")
    op.execute("ALTER TABLE leaves ALTER COLUMN type TYPE leavetype USING type::leavetype")
    op.execute("ALTER TABLE leaves ALTER COLUMN type SET DEFAULT 'ANNUAL'")
    op.alter_column('leaves', 'status',
               existing_type=postgresql.ENUM('Pending', 'Approved', 'Rejected', 'Cancelled', name='leavestatus'),
               nullable=False)
    op.create_index(op.f('ix_leaves_company_id'), 'leaves', ['company_id'], unique=False)
    op.create_index(op.f('ix_leaves_employee_id'), 'leaves', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.drop_constraint(op.f('leaves_approver_id_fkey'), 'leaves', type_='foreignkey')
    op.create_foreign_key(None, 'leaves', 'users', ['approved_by'], ['id'])
    op.drop_column('leaves', 'approver_id')
    op.add_column('shifts', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.alter_column('shifts', 'status',
               existing_type=postgresql.ENUM('Pending', 'Assigned', 'Completed', 'Cancelled', name='shiftstatus'),
               nullable=False)
    op.create_index(op.f('ix_shifts_company_id'), 'shifts', ['company_id'], unique=False)
    op.create_index(op.f('ix_shifts_employee_id'), 'shifts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.drop_constraint(op.f('shifts_approver_id_fkey'), 'shifts', type_='foreignkey')
    op.create_foreign_key(None, 'shifts', 'users', ['approved_by'], ['id'])
    op.drop_column('shifts', 'approver_id')
    # Drop existing defaults
    op.alter_column('tasks', 'status', server_default=None)
    op.alter_column('tasks', 'priority', server_default=None)

    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=taskstatus,
               existing_nullable=False,
               postgresql_using='status::taskstatus')
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=taskpriority,
               existing_nullable=False,
               postgresql_using='priority::taskpriority')

    # Set new defaults
    op.alter_column('tasks', 'status', server_default=sa.text("'PENDING'::taskstatus"))
    op.alter_column('tasks', 'priority', server_default=sa.text("'MEDIUM'::taskpriority"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Medium'::character varying"))
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='taskstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.add_column('shifts', sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.create_foreign_key(op.f('shifts_approver_id_fkey'), 'shifts', 'users', ['approver_id'], ['id'])
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_employee_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_company_id'), table_name='shifts')
    op.alter_column('shifts', 'status',
               existing_type=postgresql.ENUM('Pending', 'Assigned', 'Completed', 'Cancelled', name='shiftstatus'),
               nullable=True)
    op.drop_column('shifts', 'approved_by')
    op.add_column('leaves', sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.create_foreign_key(op.f('leaves_approver_id_fkey'), 'leaves', 'users', ['approver_id'], ['id'])
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_employee_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_company_id'), table_name='leaves')
    op.alter_column('leaves', 'status',
               existing_type=postgresql.ENUM('Pending', 'Approved', 'Rejected', 'Cancelled', name='leavestatus'),
               nullable=True)
    op.alter_column('leaves', 'type',
               existing_type=sa.Enum('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'PERSONAL', name='leavetype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('leaves', 'approved_by')
    op.drop_column('leaves', 'reason')
    # ### end Alembic commands ###
