"""add_org_structure_and_rbac

Revision ID: a67f9b490b81
Revises: 17329d64debb
Create Date: 2025-11-03 09:53:23.409287

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a67f9b490b81"
down_revision: Union[str, Sequence[str], None] = "17329d64debb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_departments_id"), "company_departments", ["id"], unique=False
    )
    op.create_table(
        "company_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["company_departments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_teams_id"), "company_teams", ["id"], unique=False)
    op.drop_table("company_settings")
    op.drop_index(op.f("ix_audit_logs_company_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.add_column("channels", sa.Column("department_id", sa.Integer(), nullable=True))
    op.add_column("channels", sa.Column("team_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "channels",
        "company_departments",
        ["department_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "channels", "company_teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("meetings", sa.Column("department_id", sa.Integer(), nullable=True))
    op.add_column("meetings", sa.Column("team_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "meetings",
        "company_departments",
        ["department_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "meetings", "company_teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("department_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("team_id", sa.Integer(), nullable=True))
    # Map legacy roles to new enum values
    op.execute("UPDATE users SET role = 'SUPERADMIN' WHERE role = 'SuperAdmin'")
    op.execute("UPDATE users SET role = 'COMPANY_ADMIN' WHERE role = 'CompanyAdmin'")
    op.execute(
        "UPDATE users SET role = 'DEPARTMENT_ADMIN' WHERE role = 'Manager' OR role = 'MANAGER'"
    )
    op.execute("UPDATE users SET role = 'EMPLOYEE' WHERE role = 'Employee'")
    # Set any remaining invalid roles to EMPLOYEE
    op.execute(
        "UPDATE users SET role = 'EMPLOYEE' WHERE role NOT IN ('SUPERADMIN', 'COMPANY_ADMIN', 'DEPARTMENT_ADMIN', 'TEAM_LEAD', 'EMPLOYEE')"
    )

    # Create the enum type first
    userrole_enum = sa.Enum(
        "SUPERADMIN",
        "COMPANY_ADMIN",
        "DEPARTMENT_ADMIN",
        "TEAM_LEAD",
        "EMPLOYEE",
        name="userrole",
    )
    userrole_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        type_=userrole_enum,
        existing_nullable=True,
        postgresql_using="role::userrole",
    )
    op.create_foreign_key(None, "users", "company_teams", ["team_id"], ["id"])
    op.create_foreign_key(
        None, "users", "company_departments", ["department_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum(
            "SUPERADMIN",
            "COMPANY_ADMIN",
            "DEPARTMENT_ADMIN",
            "TEAM_LEAD",
            "EMPLOYEE",
            name="userrole",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("users", "team_id")
    op.drop_column("users", "department_id")
    op.drop_constraint(None, "meetings", type_="foreignkey")
    op.drop_constraint(None, "meetings", type_="foreignkey")
    op.drop_column("meetings", "team_id")
    op.drop_column("meetings", "department_id")
    op.drop_constraint(None, "channels", type_="foreignkey")
    op.drop_constraint(None, "channels", type_="foreignkey")
    op.drop_column("channels", "team_id")
    op.drop_column("channels", "department_id")
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("resource_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("resource_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "details",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ip_address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("audit_logs_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("audit_logs_pkey")),
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_company_id"), "audit_logs", ["company_id"], unique=False
    )
    op.create_table(
        "company_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("timezone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("date_format", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("time_format", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("language", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "allow_employee_registration",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "require_manager_approval", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "enable_notifications", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("enable_chat", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("enable_meetings", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("max_users", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("company_settings_company_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("company_settings_pkey")),
        sa.UniqueConstraint(
            "company_id",
            name=op.f("company_settings_company_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index(op.f("ix_company_teams_id"), table_name="company_teams")
    op.drop_table("company_teams")
    op.drop_index(op.f("ix_company_departments_id"), table_name="company_departments")
    op.drop_table("company_departments")
    # ### end Alembic commands ###
