"""add_refresh_tokens_table

Revision ID: bb3a73a6e2ea
Revises: 8bee06c32eee
Create Date: 2025-10-23 12:15:04.096892

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb3a73a6e2ea"
down_revision: Union[str, Sequence[str], None] = "8bee06c32eee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_announcements_id"), table_name="announcements")
    op.drop_table("announcements")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_preferences_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_table("swap_requests")
    op.drop_index(op.f("ix_notification_digests_id"), table_name="notification_digests")
    op.drop_table("notification_digests")
    op.alter_column(
        "leaves",
        "status",
        existing_type=postgresql.ENUM(
            "Pending", "Approved", "Rejected", "Cancelled", name="leavestatus"
        ),
        nullable=True,
    )
    op.drop_index(op.f("ix_leaves_company_id"), table_name="leaves")
    op.drop_index(op.f("ix_leaves_employee_id"), table_name="leaves")
    op.drop_index(op.f("ix_leaves_id"), table_name="leaves")
    op.drop_constraint(op.f("leaves_approved_by_fkey"), "leaves", type_="foreignkey")
    op.drop_constraint(op.f("leaves_employee_id_fkey"), "leaves", type_="foreignkey")
    op.drop_column("leaves", "approved_by")
    op.drop_column("leaves", "reason")
    op.alter_column(
        "profile_update_requests", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "profile_update_requests",
        "requested_by_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "profile_update_requests",
        "request_type",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_index(
        op.f("ix_profile_update_requests_request_type"),
        table_name="profile_update_requests",
    )
    op.drop_index(
        op.f("ix_profile_update_requests_requested_by_id"),
        table_name="profile_update_requests",
    )
    op.drop_index(
        op.f("ix_profile_update_requests_user_id"), table_name="profile_update_requests"
    )
    op.drop_index(op.f("ix_shifts_company_id"), table_name="shifts")
    op.drop_index(op.f("ix_shifts_employee_id"), table_name="shifts")
    op.drop_index(op.f("ix_shifts_id"), table_name="shifts")
    op.drop_constraint(op.f("shifts_approved_by_fkey"), "shifts", type_="foreignkey")
    op.drop_column("shifts", "approved_by")
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM(
            "SUPERADMIN", "COMPANYADMIN", "MANAGER", "EMPLOYEE", name="role"
        ),
        type_=sa.String(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "SUPERADMIN", "COMPANYADMIN", "MANAGER", "EMPLOYEE", name="role"
        ),
        nullable=False,
    )
    op.add_column(
        "shifts",
        sa.Column("approved_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("shifts_approved_by_fkey"), "shifts", "users", ["approved_by"], ["id"]
    )
    op.create_index(op.f("ix_shifts_id"), "shifts", ["id"], unique=False)
    op.create_index(
        op.f("ix_shifts_employee_id"), "shifts", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_shifts_company_id"), "shifts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_profile_update_requests_user_id"),
        "profile_update_requests",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_update_requests_requested_by_id"),
        "profile_update_requests",
        ["requested_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_update_requests_request_type"),
        "profile_update_requests",
        ["request_type"],
        unique=False,
    )
    op.alter_column(
        "profile_update_requests",
        "request_type",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "profile_update_requests",
        "requested_by_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "profile_update_requests", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "leaves", sa.Column("reason", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "leaves",
        sa.Column("approved_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("leaves_employee_id_fkey"), "leaves", "users", ["employee_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("leaves_approved_by_fkey"), "leaves", "users", ["approved_by"], ["id"]
    )
    op.create_index(op.f("ix_leaves_id"), "leaves", ["id"], unique=False)
    op.create_index(
        op.f("ix_leaves_employee_id"), "leaves", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_leaves_company_id"), "leaves", ["company_id"], unique=False
    )
    op.alter_column(
        "leaves",
        "status",
        existing_type=postgresql.ENUM(
            "Pending", "Approved", "Rejected", "Cancelled", name="leavestatus"
        ),
        nullable=False,
    )
    op.create_table(
        "notification_digests",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "digest_type",
            postgresql.ENUM("DAILY", "WEEKLY", name="digesttype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "SENT", "FAILED", name="digeststatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "notification_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "notification_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "scheduled_for", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("notification_digests_company_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("notification_digests_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_digests_pkey")),
    )
    op.create_index(
        op.f("ix_notification_digests_id"), "notification_digests", ["id"], unique=False
    )
    op.create_table(
        "swap_requests",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "requester_shift_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("target_shift_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("requester_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "target_employee_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "APPROVED", "REJECTED", "CANCELLED", name="swapstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("reviewed_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "reviewed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("swap_requests_company_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], name=op.f("swap_requests_requester_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["requester_shift_id"],
            ["shifts.id"],
            name=op.f("swap_requests_requester_shift_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("swap_requests_reviewed_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["target_employee_id"],
            ["users.id"],
            name=op.f("swap_requests_target_employee_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_shift_id"],
            ["shifts.id"],
            name=op.f("swap_requests_target_shift_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("swap_requests_pkey")),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sender_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("receiver_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_read", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("chat_messages_company_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"], ["users.id"], name=op.f("chat_messages_receiver_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("chat_messages_sender_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_messages_pkey")),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("mute_all", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "digest_mode", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("push_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "notification_types",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("notification_preferences_company_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("notification_preferences_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_preferences_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("notification_preferences_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_notification_preferences_id"),
        "notification_preferences",
        ["id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "TASK_ASSIGNED",
                "TASK_COMPLETED",
                "TASK_OVERDUE",
                "SHIFT_SCHEDULED",
                "SHIFT_SWAP_REQUESTED",
                "SHIFT_SWAP_APPROVED",
                "SHIFT_SWAP_REJECTED",
                "LEAVE_APPROVED",
                "LEAVE_REJECTED",
                "SYSTEM_MESSAGE",
                "ADMIN_MESSAGE",
                name="notificationtype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("UNREAD", "READ", name="notificationstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("notifications_company_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("notifications_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notifications_pkey")),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_table(
        "announcements",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("announcements_company_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("announcements_created_by_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("announcements_pkey")),
    )
    op.create_index(op.f("ix_announcements_id"), "announcements", ["id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "POLICY", "PAYSLIP", "NOTICE", "OTHER", name="documenttype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("access_role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("documents_company_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("documents_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("documents_pkey")),
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    # ### end Alembic commands ###
