"""add profile_update_requests table

Revision ID: ea34083b61dd
Revises: 2561fe908fb1
Create Date: 2025-09-26 19:37:17.571539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea34083b61dd'
down_revision: Union[str, Sequence[str], None] = '2561fe908fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.alter_column('profile_update_requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_update_requests', 'requested_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_update_requests', 'request_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_profile_update_requests_request_type'), 'profile_update_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_profile_update_requests_requested_by_id'), 'profile_update_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_profile_update_requests_user_id'), 'profile_update_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_update_requests_user_id'), table_name='profile_update_requests')
    op.drop_index(op.f('ix_profile_update_requests_requested_by_id'), table_name='profile_update_requests')
    op.drop_index(op.f('ix_profile_update_requests_request_type'), table_name='profile_update_requests')
    op.alter_column('profile_update_requests', 'request_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profile_update_requests', 'requested_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_update_requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('document_type', postgresql.ENUM('CONTRACT', 'POLICY', 'TRAINING', 'CERTIFICATE', 'OTHER', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('access_level', postgresql.ENUM('PUBLIC', 'PRIVATE', 'RESTRICTED', name='accesslevel'), server_default=sa.text("'PRIVATE'::accesslevel"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('documents_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('documents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    # ### end Alembic commands ###
