"""Add invite model for company user management

Revision ID: f19bf976d61f
Revises: 56c6bfba7c2b
Create Date: 2025-12-05 15:35:42.266483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f19bf976d61f'
down_revision: Union[str, Sequence[str], None] = '56c6bfba7c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_tokens_id'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    
    # Fix inventory_items status enum case change
    op.execute("UPDATE inventory_items SET status = 'IN_STOCK' WHERE status = 'in_stock'")
    op.execute("UPDATE inventory_items SET status = 'LOW_STOCK' WHERE status = 'low_stock'")
    op.execute("UPDATE inventory_items SET status = 'OUT_OF_STOCK' WHERE status = 'out_of_stock'")
    op.alter_column('inventory_items', 'status',
               existing_type=postgresql.ENUM('in_stock', 'low_stock', 'out_of_stock', name='inventory_status'),
               type_=sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', name='inventorystatus'),
               nullable=True)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='purchase_order_status'),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='purchaseorderstatus'),
               existing_nullable=True)
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.alter_column('vendors', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', name='vendor_status'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', name='vendorstatus'),
               existing_nullable=True)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    
    # Add invite table
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.alter_column('vendors', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='vendorstatus'),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', name='vendor_status'),
               existing_nullable=True)
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='purchaseorderstatus'),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='purchase_order_status'),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.alter_column('inventory_items', 'status',
               existing_type=sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', name='inventorystatus'),
               type_=postgresql.ENUM('in_stock', 'low_stock', 'out_of_stock', name='inventory_status'),
               nullable=False)
    op.create_table('reset_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reset_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reset_tokens_id'), 'reset_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
