"""phase2 attendance leave updates

Revision ID: phase2_attendance_leave_updates
Revises: 11bf165b1dde
Create Date: 2024-06-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'phase2_attendance_leave_updates'
down_revision = '11bf165b1dde'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create attendance status enum
    attendance_status = postgresql.ENUM('CLOCKED_IN', 'CLOCKED_OUT', name='attendance_status')
    attendance_status.create(op.get_bind())

    # Add columns to attendance
    op.add_column('attendance', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('ip_address', sa.String(), nullable=True))

    # Alter status column to enum
    op.alter_column('attendance', 'status',
               existing_type=sa.String(length=50),
               type_=attendance_status,
               existing_nullable=False,
               server_default='CLOCKED_OUT',
               postgresql_using='status::attendance_status')

    # Create leave type enum
    leave_type = postgresql.ENUM('VACATION', 'SICK', 'PERSONAL', 'UNPAID', name='leave_type')
    leave_type.create(op.get_bind())

    # Create leave status enum
    leave_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status')
    leave_status.create(op.get_bind())

    # Handle leave type conversion with value mapping
    # First, change column to text to allow updates
    op.alter_column('leaves', 'type',
               existing_type=postgresql.ENUM('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'PERSONAL', name='leavetype'),
               type_=sa.Text(),
               existing_nullable=False,
               server_default='VACATION')

    # Update existing values to match new enum
    op.execute("UPDATE leaves SET type = 'VACATION' WHERE type = 'ANNUAL'")
    op.execute("UPDATE leaves SET type = 'PERSONAL' WHERE type IN ('MATERNITY', 'PATERNITY')")
    # SICK and PERSONAL remain the same

    # Drop the old enum
    op.execute("DROP TYPE IF EXISTS leavetype CASCADE")

    # Drop the old enum type if exists
    op.execute("DROP TYPE IF EXISTS leave_type CASCADE")
    # Create new enum
    leave_type = sa.Enum('VACATION', 'SICK', 'PERSONAL', 'UNPAID', name='leave_type')
    leave_type.create(op.get_bind())
    # Create new enum and alter column using raw SQL to avoid default issues
    # Handle leave type conversion - convert old enum to new enum
    op.execute("ALTER TABLE leaves ALTER COLUMN type DROP DEFAULT")
    op.execute("ALTER TABLE leaves ALTER COLUMN type TYPE VARCHAR")
    op.execute("ALTER TABLE leaves ALTER COLUMN type TYPE leave_type USING type::leave_type")
    op.execute("ALTER TABLE leaves ALTER COLUMN type SET DEFAULT 'VACATION'")

    # Handle leave status conversion - convert old enum to new enum
    op.execute("ALTER TABLE leaves ALTER COLUMN status TYPE VARCHAR")
    op.execute("ALTER TABLE leaves ALTER COLUMN status TYPE leave_status USING status::leave_status")
    op.alter_column('leaves', 'status',
               existing_type=leave_status,
               nullable=False,
               server_default='PENDING')
    # approved_by and reason columns were already dropped in phase 1 migration

    # Create index on leaves
    op.create_index('ix_leaves_company_status', 'leaves', ['company_id', 'status'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index
    op.drop_index('ix_leaves_company_status', table_name='leaves')

    # Revert leave columns
    op.alter_column('leaves', 'reason',
               existing_type=sa.Text(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('leaves', 'approver_id',
               new_column_name='approved_by',
               existing_type=sa.Integer(),
               existing_nullable=True)
    op.alter_column('leaves', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status'),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'),
               existing_nullable=False)
    op.alter_column('leaves', 'type',
               existing_type=postgresql.ENUM('VACATION', 'SICK', 'PERSONAL', 'UNPAID', name='leave_type'),
               type_=postgresql.ENUM('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'PERSONAL', name='leavetype'),
               existing_nullable=False)

    # Drop enums
    leave_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status')
    leave_status.drop(op.get_bind())
    leave_type = postgresql.ENUM('VACATION', 'SICK', 'PERSONAL', 'UNPAID', name='leave_type')
    leave_type.drop(op.get_bind())

    # Revert attendance
    op.alter_column('attendance', 'status',
               existing_type=postgresql.ENUM('CLOCKED_IN', 'CLOCKED_OUT', name='attendance_status'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('attendance', 'ip_address')
    op.drop_column('attendance', 'lng')
    op.drop_column('attendance', 'lat')

    attendance_status = postgresql.ENUM('CLOCKED_IN', 'CLOCKED_OUT', name='attendance_status')
    attendance_status.drop(op.get_bind())

    # ### end Alembic commands ###
